
CREATE TABLE Employee(
    EMPID INT PRIMARY KEY,
    NAME VARCHAR(15) NOT NULL,
    ADDR VARCHAR(20) NOT NULL CHECK (ADDR NOT LIKE '%UTTAM NAGAR%'),
    CITY VARCHAR(15) CHECK (CITY IN ('DEL','GGN','FBD','NOIDA')),
    PHNO VARCHAR(10) UNIQUE,
    EMAIL VARCHAR(20) CHECK (EMAIL LIKE '%GMAIL.COM' OR EMAIL LIKE '%YAHOO.COM'),
    DOB VARCHAR(15) CHECK (DOB <='1-JAN-2000')   
)
SELECT * FROM Employee

INSERT INTO Employee
    VALUES(1001,'JOHN','DELHI','DEL','45678989','JH@GMAIL.COM','02-08,1999')
    
INSERT INTO Employee
    VALUES(1002,'TOM','UP','FBD','97523234','TOM@GMAIL.COM','01-08,1998')

INSERT INTO Employee
    VALUES(1003,'BOB','HARYANA','GGN','9750987','BOB@GMAIL.COM','01-10-2000')

INSERT INTO Employee
    VALUES(1004,'BOB','DELHI','NOIDA','975097290','BOB@YAHOO.COM','01-05-2000')


CREATE TABLE EDet(
    EMPID INT,
    DEPT VARCHAR(15) DEFAULT 'TEMP' CHECK (DEPT IN ('HR','MIS','OPS','IT','ADMIN','TEMP')),
    DESI VARCHAR(10) CHECK (DESI IN ('ASSO','MGR','VP','DIR')),
    BASIC DECIMAL(10,2) CHECK (BASIC>=20000),
    DOJ  DATE,
)


INSERT INTO EDet
VALUES(1001,'HR','ASSO',22000,'2023-05-23')

INSERT INTO EDet
VALUES(1002,'MIS','MGR',24000,'2022-02-15')

INSERT INTO EDet
VALUES(1003,'OPS','VP',25000,'2021-12-28')

INSERT INTO EDet
VALUES(1003,'IT','DIR',26000,'2020-05-12')

INSERT INTO EDet
VALUES(1004,'IT','DIR',29000,'2021-07-11')

INSERT INTO EDet
VALUES(1007,'TEMP','VP',29000,'2022-07-11')


SELECT * FROM Employee
SELECT * FROM EDet

-------- INNER JOIN(GIVES COMMON RECORDS BETWEEN TWO TABLES -----------

SELECT E.NAME,D.DEPT,D.DESI,D.BASIC,D.DOJ FROM 
Employee E
inner join EDet D on D.EMPID=E.EMPID

------------  LEFT JOIN (RETURNS ALL THE VALUES FROM THE LEFT TABLE SIDE AND MATCHING FROM THE RIGHT TABLE 
--------------IF NOT MATCH THEN GIVES NULL VALUES

SELECT E.NAME,E.CITY,E.PHNO,D.DESI,D.BASIC FROM Employee E
LEFT JOIN EDet D on E.EMPID = D.EMPID

-----------------RIGHT JOIN (RETURNS ALL THE VALUES FROM THE RIGHT TABLE AND MATCHING FROM THE LEFT TABLE
---------------- IF NOT MATCHING THEN GIVES NULL VALUES

SELECT E.NAME,E.EMAIL,E.DOB,D.DOJ,D.BASIC FROM EMPLOYEE E
RIGHT JOIN EDet D on E.EMPID = D.EMPID

------------------ FULL JOIN (RETURNS ALL THE VALUES FROM THE BOTH TABLE -------
SELECT E.NAME,E.CITY,D.DEPT,D.DESI,D.BASIC FROM Employee E
FULL JOIN EDet D on E.EMPID = D.EMPID

-------------------CROSS JOIN OR CARTESIAN JOIN ( THE CARTESIAN PRODUCT OF THE SETS OF RECORDS FROM THE TWO
-------------------- OR MORE JOINED TABLES
------------------------------ CROSS JOIN + WHERE = INNER

SELECT E.ADDR,E.CITY,D.DEPT,D.BASIC FROM Employee E
CROSS JOIN EDet D
WHERE E.EMPID = D.EMPID

SELECT ADDR,DEPT FROM Employee
CROSS JOIN EDet



------------------- SELF JOIN (USED TO JOIN A TABLE ITSELF ONLY) --------------------------

SELECT A.NAME,B.ADDR FROM Employee A,Employee B
where A.EMPID = B.EMPID

SELECT * FROM Employee
SELECT * FROM EDet

-----------------------------------------------------------------------------------------------------------------------
       ------ UNION CLAUSE (IT WILL RETURNS ALL THE SELECT STATEMENT WITHOUT RETURNING DUPLICATE VALUES) ------- 
	   
SELECT E.NAME,E.ADDR,D.DEPT FROM Employee E
LEFT JOIN EDet D ON E.EMPID = D.EMPID
UNION
SELECT E.NAME,E.ADDR,D.DEPT FROM Employee E
RIGHT JOIN EDet D ON E.EMPID=D.EMPID


SELECT EMP.NAME,EMP.CITY,EMP_SAL.DEPT,EMP_SAL.BASIC
FROM Employee EMP
LEFT JOIN EDet EMP_SAL
ON EMP.EMPID=EMP_SAL.EMPID
UNION
SELECT EMP.NAME,EMP.CITY,EMP_SAL.DEPT,EMP_SAL.BASIC
FROM Employee EMP
RIGHT JOIN EDet EMP_SAL
ON EMP.EMPID=EMP_SAL.EMPID

--------------UNION ALL(IT WILL RETURNS ALL THE VALUES FROM THE TWO MORE SELECT STATEMENT WITH RETURNING 
-------------- DUPLICATE VALUES ALSO)

SELECT E.NAME,E.CITY,E.EMAIL,D.DEPT,D.DOJ,D.BASIC FROM Employee E
CROSS JOIN EDet D
WHERE E.EMPID=D.EMPID
UNION ALL
SELECT E.NAME,E.CITY,E.EMAIL,D.DEPT,D.DOJ,D.BASIC FROM Employee E
RIGHT JOIN EDet D ON E.EMPID=D.EMPID

------------------INTERSECT CLAUSE(IT WILL RETURNS COMMON VALUES FROM BETWEEN TWO OR MORE SELECT STATEMENT) ---------

SELECT E.NAME,E.ADDR,E.EMAIL,D.BASIC,D.DOJ FROM Employee E
INNER JOIN EDet D ON E.EMPID=D.EMPID
INTERSECT
SELECT E.NAME,E.ADDR,E.EMAIL,D.BASIC,D.DOJ FROM Employee E,EDet D
where E.EMPID=D.EMPID

----------------------- EXCEPT (IT WILL RETUENS ONLY FIRST SELECT STATEMENT VALUES)

----- The SQL EXCEPT clause/operator is used to combine two SELECT statements and returns
----- rows from the first SELECT statement that are not returned by the second SELECT
----- statement. This means EXCEPT returns only rows which are not available in second SELECT
----- statement.


SELECT EMP.NAME,EMP.CITY,EMP_SAL.DEPT,EMP_SAL.DESI
FROM Employee EMP
LEFT JOIN EDet EMP_SAL
ON EMP.EMPID=EMP_SAL.EMPID
EXCEPT
SELECT EMP.NAME,EMP.CITY,EMP_SAL.DEPT,EMP_SAL.DESI
FROM Employee EMP
RIGHT JOIN EDet EMP_SAL
ON EMP.EMPID=EMP_SAL.EMPID 

-----------------------------------------------------------------------------------------------------------------------
---------------------------------  INDEXES -----------------
---- THROUGH INDEXES WE CAN FETCH THE DATA FASTLY
---- IF WE CAN DELETE THE index it will effect on table.
---- 

